### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by szabogyula** [pdias/FOSSamlBundle#1]
Hi Paulo,

I want to use your saml bundle, but i can't figure out, how should I use it.

Can you drop any example of security.yml, or a short step by step doc?

Thanks a lot!

**Comment by pdias** [comment]
Hello,

Hello, I am out of the office.
Tomorrow or in the weekend, I send you the information you need.

Thanks.

2014-06-05 13:29 GMT+01:00 Gyula Szabó notifications@github.com:

> Hi Paulo,
> 
> I want to use your saml bundle, but i can't figure out, how should I use
> it.
> 
> Can you drop any example of security.yml, or a short step by step doc?
> 
> Thanks a lot!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pdias/FOSSamlBundle/issues/1.

## 

Paulo Dias

**Comment by andrius-kulbis** [comment]
Hello,if it is possible, I would also like the information how to use this bundle

**Comment by supakitk** [comment]
I would like to see example or documentation as well.

Thanks so much!

**Comment by pdias** [comment]
Sorry for the delay in response, only now I had the opportunity.
I changed some things in this bundle already created some documentation.

Please see: https://github.com/pdias/SamlBundle

The installation by composer still does not work, as soon as I can handle it.
